baseURL = 'https://nextadventure.io/'
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
defaultContentLanguage = 'en'
title = "Caro & the Viking | Mar 2024"
theme = "hugo-scroll"

[languages]
  [languages.en]
    title = "Caro & the Viking | Mar 2024"
    languageName = "English"
    weight = 1
  [languages.es]
    title = "Caro & the Viking | Mar 2024"
    languageName = "Spanish"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/boda179.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/boda179.png"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    title = "Caro & The Viking | Mar 2024"
    description = "Caro & The Viking | Mar 2024"
    hidedesignbyline = true

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false
    
    [params.meta]
        keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
